### ISSUE TITLE
System.InvalidProgramException: 'Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally

### ISSUE THREAD

**Issue by Guoyongjie** [DevExpress-Examples/xamarin-forms-demo-app#4]
To run the application:

1.Obtain your NuGet feed URL. --- done
2.Register the DevExpress NuGet feed as a package source. ---done
3.Restore all NuGet packages for the solution. ---done.

I reported an exception while running

System.InvalidProgramException: 'Invalid IL code in Mono.SystemDependencyProvider:Initialize (): IL_002e: endfinally

Microsoft Visual Studio Enterprise 2022 (64 位) - Preview
版本 17.1.0 Preview 1.0

Please help me, thanks

**Comment by DmitryRomenskiy** [comment]
Hello @Guoyongjie,

Thank you for your report. I quickly searched for known issues, but I do not see anything similar in our knowledge base. However, if you are using MAUI, it may be related to its version. We supported previews 9 and 10 only recently. See https://community.devexpress.com/blogs/mobile/archive/2021/11/16/devexpress-ui-controls-support-the-latest-microsoft-dot-net-maui-preview-10.aspx.

If this does not help, I believe that the best way to proceed is to refer to our Support Center (http://www.devexpress.com/ask). Submit a new ticket there and attach a sample that demonstrates how to reproduce the issue. Our support team will be happy to help.

**Comment by Guoyongjie** [comment]
@DmitryRomenskiy Thanks for the answer. I'll pull the latest code and try again
